baseurl = "localhost:1313"
#baseurl = "https://livinglightministriesph.org/"
title = "Living Light Ministries Inc"
theme = "hugo-universal-theme"
languageCode = "en-us"
# Enable comments by entering your Disqus shortname
#disqusShortname = "devcows"
# Enable Google Analytics by entering your tracking code
googleAnalytics = ""


# Define the number of posts per page
paginate = 10

[params]
    viewMorePostLink = "/leadership/"

    author = "DevCows"

    # Google Maps API key (if not set will default to not passing a key.)
    googleMapsApiKey = ""

    # Style options: default (light-blue), blue, green, marsala, pink, red, turquoise, violet
    style = "blue"

    # Since this template is static, the contact form uses www.formspree.io as a
    # proxy. The form makes a POST request to their servers to send the actual
    # email. Visitors can send up to a 1000 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - set your email address under 'email' below
    # - upload the generated site to your server
    # - send a dummy email yourself to confirm your account
    # - click the confirm link in the email from www.formspree.io
    # - you're done. Happy mailing!
    #
    # Enable the contact form by entering your Formspree.io email
    email = "livinglight.cebu@gmail.com"
    #email = "your@email.com"


    about_us = "<p>Living Light Ministries is an interdenominational ministry that serves the body of Christ in Evangelism through Radio, Television and Crusade; Teaching, and Revivals in the Philippines and around the world.</p> <p>The Living Light Christian Fellowship is a family church that believes in Salvation, Healing, The Baptism and the Gifts of the Holy Spirit. </p> <p>We also believe that Israel is God's chosen people, the real branch; and that we as wild olives have been grafted in their place in the olive tree. One day God is going to restore Israel to its place.</p><p>While waiting for that, it is our duty to pray, intercede, help and love God's chosen people-Israel. We pray for the peace of Jerusalem, God's Holy City.</p>"
    copyright = "Copyright © 2017-2018<br/> Living Light Ministries Inc."
   schedule = "<p><b>Sunday Service: 10:00 AM – 12:00 NN</b> </p>"
   streetloc = "<p><iframe src=https://www.google.com/maps/embed?pb=!1m0!3m2!1sen!2sph!4v1485904644655!6m8!1m7!1sOYlUwm7JB9NMV8HfPWNbIQ!2m2!1d10.29612410049556!2d123.9019572177309!3f288.75!4f4.230000000000004!5f0.7820865974627469 width=350 height=350 frameborder=0 style=border:0 allowfullscreen></iframe></p>"

    # Format dates with Go's time formatting
    date_format = "January 2, 2006"

    logo = "img/logo.png"
    address = """<p><strong>Living Light Ministries Inc.</strong>
        <br>2nd Floor Maryjoy Blg.
        <br>46 D. Jackosalem St.
        <br>Cebu City
        <br><strong>Philippines</strong>
        <br>+(63) 32 231-2035
        <br><strong>SEC REGISTRATION NUMBER : CEO0002763</strong>
      </p>
      """
    latitude = "10.2961241"
    longitude = "123.9019572"

[Permalinks]
    # blog = "/blog/:year/:month/:day/:filename/"
    leadership = "/leadership/:filename/"

# Enable external url logo hosting ex. Amazon S3 AWS, if disabled will use default logo located in /themes/static/img/
[params.extlogo]
    enable = true
    url ="https://webcdn.bual.at/llmi/web_src/logo.jpg"
    urlsm ="https://webcdn.bual.at/llmi/web_src/logo.jpg"

# Enable serving of images and other static content to a non-cookie url, if disabled it will use the local file path
[params.cdn]
    enable = true
    cdnurl = "https://webcdn.bual.at/llmi/web_src/static/"

# Enable modifying the Facebook OG Tag according to your needs
[params.ogtagmod]
    enable = true
    title = "Welcome to Living Light Ministries Official Website"
    sitetitle = "Living Light Ministries Official Website"
    baseurl = "https://livinglightministriesph.org"
    ogimg = "https://webcdn.bual.at/llmi/static/img/photogrid.jpg"
    desc = "Living Light Ministries is an interdenominational ministry that serves the body of Christ in Evangelism through Radio, Television and Crusade; Teaching, and Revivals in the Philippines and around the world.The Living Light Christian Fellowship is a family church that believes in Salvation, Healing, The Baptism and the Gifts of the Holy Spirit."

[params.location]    
    locale ="en_PH"

[[params.menu]]
    name = "Home"
    url  = "/"
    weight = 1

[[params.menu]]
    name = "Statement of Faith"
    url  = "/faq/"
    weight = 2

[[params.menu]]
    name = "Leadership"
    url  = "/leadership/"
    weight = 3

[[params.menu]]
    name = "Blog"
    #url  = "/blog/"
    url  = "https://livinglightministriesblog.tumblr.com/"
    newtab = "true"
    weight = 4

[[params.menu]]
    name = "Contact"
    url  = "/contact/"
    weight = 5

# Enable and disable widgets for the right sidebar
[params.widgets]
    categories = false
    tags = false
    search = false

[params.carousel]
    enable = true
    # All carousel items are defined in their own files. You can find example items
    # at 'exampleSite/data/carousel'.
    # For more informtion take a look at the README.

[params.features]
    enable = true
    # All features are defined in their own files. You can find example items
    # at 'exampleSite/data/features'.
    # For more informtion take a look at the README.

[params.testimonials]
    enable = false
    # All testimonials are defined in their own files. You can find example items
    # at 'exampleSite/data/testimonials'.
    # For more informtion take a look at the README.
    title = "Testimonials"
    subtitle = "We have worked with many clients and we always like to hear they come out from the cooperation happy and satisfied. Have a look what our clients said about us."

[params.see_more]
    enable = true
    icon = "fa fa-file-code-o"
    title = "Do you want to experience breakthrough in your life?"
    subtitle = "Come visit us! You are very much welcome."
    link_url = "/contact/"
    link_text = "Give me the directions"

[params.clients]
    enable = true
    # All clients are defined in their own files. You can find example items
    # at 'exampleSite/data/clients'.
    # For more informtion take a look at the README.
    title = "You can Find us on"
    subtitle = ""

[params.recent_posts]
    enable = true
    title = "Our Leaders and Staff"
    subtitle = ""


